"""
score_synthetic_applicants.py

Scores synthetic loan applicants generated by Gemini and ChatGPT
through the Phase 4 LightGBM champion model and Phase 6 decision engine.

Validates out-of-sample model performance against known risk profiles:
    - Rows 1-15:  LOW RISK (should score < 0.30, decision: Approved)
    - Rows 16-35: MODERATE RISK (should score 0.30-0.50, mixed decisions)
    - Rows 36-50: HIGH RISK (should score > 0.50, decision: Denied)

Output: outputs/synthetic_scoring_results.csv

Usage:
    python3 score_synthetic_applicants.py
"""

import os
import joblib
import pandas as pd
import numpy as np

from utils.decision_classifier import classify_all, extract_all_reason_codes

# ── Configuration ─────────────────────────────────────────────────────────────
CHAMPION_MODEL_PATH = os.path.join("models", "champion_model.pkl")
GEMINI_CSV          = os.path.join("data", "processed", "gemini_test_applicants.csv")
CHATGPT_CSV         = os.path.join("data", "processed", "chatgpt_test_applicants.csv")
OUTPUT_CSV          = os.path.join("outputs", "synthetic_scoring_results.csv")

# Known risk tier boundaries based on how we designed the synthetic data
LOW_RISK_ROWS      = (0, 15)    # rows 1-15
MODERATE_RISK_ROWS = (15, 35)   # rows 16-35
HIGH_RISK_ROWS     = (35, 50)   # rows 36-50

FEATURE_COLUMNS = [
    "term_months", "interest_rate", "loan_amount", "sba_guarantee_pct",
    "business_age_mature", "loan_size_bucket_micro", "naics_sector_62",
    "loan_size_bucket_large", "borr_state_FL", "business_age_startup",
    "borr_state_TX", "jobs_supported", "business_age_established",
    "loan_size_bucket_small", "borr_state_CA", "loan_size_bucket_medium",
    "business_age_new", "naics_sector_48", "borr_state_WI", "borr_state_NJ",
    "borr_state_NY", "naics_sector_71", "naics_sector_52", "borr_state_WA",
    "naics_sector_45", "borr_state_MN",
]


def load_champion_model():
    """Load the Phase 4 LightGBM champion model from disk."""
    if not os.path.exists(CHAMPION_MODEL_PATH):
        raise FileNotFoundError(
            f"Champion model not found at {CHAMPION_MODEL_PATH}. "
            "Ensure Phase 4 completed successfully."
        )
    model = joblib.load(CHAMPION_MODEL_PATH)
    print(f"[scorer] Champion model loaded: {CHAMPION_MODEL_PATH}")
    return model


def score_dataframe(df: pd.DataFrame, model, source: str) -> pd.DataFrame:
    """
    Score a synthetic applicant DataFrame using the champion model.

    Parameters
    ----------
    df : pd.DataFrame
        Synthetic applicant data with 26 feature columns.
    model : object
        Fitted LightGBM champion model.
    source : str
        Label for the data source ('Gemini' or 'ChatGPT').

    Returns
    -------
    pd.DataFrame
        Input DataFrame with predicted_prob, decision, and reason_codes added.
    """
    missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"[scorer] Missing columns in {source} data: {missing}")

    X = df[FEATURE_COLUMNS]
    df = df.copy()
    df["predicted_prob"] = model.predict_proba(X)[:, 1]
    df["source"]         = source
    df = classify_all(df)
    df["reason_codes"]   = extract_all_reason_codes(df)
    return df


def validate_risk_tiers(df: pd.DataFrame, source: str) -> None:
    """
    Check whether the model correctly identified the designed risk tiers.

    Prints a tier-by-tier accuracy summary showing what percentage of
    intentionally low/moderate/high risk applicants were correctly classified.

    Parameters
    ----------
    df : pd.DataFrame
        Scored DataFrame with decision column.
    source : str
        Label for the data source.
    """
    print(f"\n── {source} Risk Tier Validation ─────────────────────────────")

    tiers = [
        ("LOW RISK",      slice(*LOW_RISK_ROWS),      "Approved"),
        ("MODERATE RISK", slice(*MODERATE_RISK_ROWS), None),
        ("HIGH RISK",     slice(*HIGH_RISK_ROWS),      "Denied"),
    ]

    for tier_name, slc, expected_decision in tiers:
        tier_df = df.iloc[slc]
        if len(tier_df) == 0:
            print(f"  {tier_name}: no rows in this tier")
            continue

        mean_prob = tier_df["predicted_prob"].mean()
        decisions = tier_df["decision"].value_counts().to_dict()

        print(f"\n  {tier_name} ({len(tier_df)} applicants):")
        print(f"    Mean predicted prob: {mean_prob:.4f}")
        print(f"    Decisions: {decisions}")

        if expected_decision:
            correct = (tier_df["decision"] == expected_decision).sum()
            pct     = correct / len(tier_df) * 100
            print(f"    Correctly classified as '{expected_decision}': "
                  f"{correct}/{len(tier_df)} ({pct:.1f}%)")


def print_summary(combined: pd.DataFrame) -> None:
    """Print overall scoring summary across both sources."""
    print("\n" + "=" * 60)
    print("  SYNTHETIC SCORING SUMMARY")
    print("=" * 60)

    for source in ["Gemini", "ChatGPT"]:
        subset = combined[combined["source"] == source]
        if len(subset) == 0:
            continue
        print(f"\n  {source} ({len(subset)} applicants):")
        print(f"    Mean predicted prob: {subset['predicted_prob'].mean():.4f}")
        print(f"    Min: {subset['predicted_prob'].min():.4f} "
              f"Max: {subset['predicted_prob'].max():.4f}")
        for decision, count in subset["decision"].value_counts().items():
            print(f"    {decision}: {count} ({count/len(subset)*100:.1f}%)")

    print(f"\n  Combined ({len(combined)} applicants):")
    print(f"    Mean predicted prob: {combined['predicted_prob'].mean():.4f}")
    for decision, count in combined["decision"].value_counts().items():
        print(f"    {decision}: {count} ({count/len(combined)*100:.1f}%)")
    print("=" * 60)


if __name__ == "__main__":
    print("=" * 60)
    print("  SYNTHETIC APPLICANT SCORING")
    print("=" * 60)

    # Load champion model
    model = load_champion_model()

    # Load and score both datasets
    print("\n[scorer] Loading synthetic datasets...")
    gemini_df  = pd.read_csv(GEMINI_CSV)
    chatgpt_df = pd.read_csv(CHATGPT_CSV)
    print(f"[scorer] Gemini: {len(gemini_df)} rows | "
          f"ChatGPT: {len(chatgpt_df)} rows")

    print("\n[scorer] Scoring Gemini applicants...")
    gemini_scored = score_dataframe(gemini_df, model, "Gemini")

    print("\n[scorer] Scoring ChatGPT applicants...")
    chatgpt_scored = score_dataframe(chatgpt_df, model, "ChatGPT")

    # Validate risk tier accuracy
    validate_risk_tiers(gemini_scored, "Gemini")
    validate_risk_tiers(chatgpt_scored, "ChatGPT")

    # Combine and save
    combined = pd.concat([gemini_scored, chatgpt_scored], ignore_index=True)

    # Convert reason_codes list to string for CSV
    combined["reason_codes"] = combined["reason_codes"].apply(
        lambda x: " | ".join(x) if x else ""
    )

    os.makedirs("outputs", exist_ok=True)
    combined.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[scorer] Results saved: {OUTPUT_CSV}")

    # Print summary
    print_summary(combined)

    print("\n  Ready for Phase 7 — Dashboards.")