"""
score_synthetic_applicants.py

Scores synthetic loan applicants generated by four AI sources
(Gemini, ChatGPT, Claude, Copilot) through the Phase 4 LightGBM
champion model and Phase 6 decision engine.

Validates out-of-sample model performance against known risk profiles:
    - Rows 1-15:  LOW RISK (should score < 0.30, decision: Approved)
    - Rows 16-35: MODERATE RISK (should score 0.30-0.50, mixed decisions)
    - Rows 36-50: HIGH RISK (should score > 0.50, decision: Denied)

Output: outputs/synthetic_scoring_results.csv

Usage:
    python3 score_synthetic_applicants.py
"""

import os
import joblib
import pandas as pd
import numpy as np

from utils.decision_classifier import classify_all, extract_all_reason_codes
from utils.scorer import preprocess_and_scale

# ── Configuration ─────────────────────────────────────────────────────────────
CHAMPION_MODEL_PATH = os.path.join("models", "champion_model.pkl")
OUTPUT_CSV          = os.path.join("outputs", "synthetic_scoring_results.csv")

# All four synthetic dataset paths
SYNTHETIC_SOURCES = {
    "Gemini":  os.path.join("data", "processed", "gemini_test_applicants.csv"),
    "ChatGPT": os.path.join("data", "processed", "chatgpt_test_applicants.csv"),
    "Claude":  os.path.join("data", "processed", "claude_test_applicants.csv"),
    "Copilot": os.path.join("data", "processed", "copilot_test_applicants.csv"),
}

# Known risk tier boundaries based on how we designed the synthetic data
LOW_RISK_ROWS      = (0, 15)    # rows 1-15
MODERATE_RISK_ROWS = (15, 35)   # rows 16-35
HIGH_RISK_ROWS     = (35, 50)   # rows 36-50

FEATURE_COLUMNS = [
    "term_months", "interest_rate", "loan_amount", "sba_guarantee_pct",
    "business_age_mature", "loan_size_bucket_micro", "naics_sector_62",
    "loan_size_bucket_large", "borr_state_FL", "business_age_startup",
    "borr_state_TX", "jobs_supported", "business_age_established",
    "loan_size_bucket_small", "borr_state_CA", "loan_size_bucket_medium",
    "business_age_new", "naics_sector_48", "borr_state_WI", "borr_state_NJ",
    "borr_state_NY", "naics_sector_71", "naics_sector_52", "borr_state_WA",
    "naics_sector_45", "borr_state_MN",
]


def load_champion_model():
    """Load the Phase 4 LightGBM champion model from disk."""
    if not os.path.exists(CHAMPION_MODEL_PATH):
        raise FileNotFoundError(
            f"Champion model not found at {CHAMPION_MODEL_PATH}. "
            "Ensure Phase 4 completed successfully."
        )
    model = joblib.load(CHAMPION_MODEL_PATH)
    print(f"[scorer] Champion model loaded: {CHAMPION_MODEL_PATH}")
    return model


def score_dataframe(df: pd.DataFrame, model, source: str) -> pd.DataFrame:
    """
    Scale and score a synthetic applicant DataFrame using the champion model.

    Applies Phase 3 z-score scaling via preprocess_and_scale() before
    passing features to the model — same transformation used in production.

    Parameters
    ----------
    df : pd.DataFrame
        Raw synthetic applicant data with 26 feature columns.
    model : object
        Fitted LightGBM champion model.
    source : str
        Label for the data source ('Gemini', 'ChatGPT', 'Claude', 'Copilot').

    Returns
    -------
    pd.DataFrame
        Input DataFrame with predicted_prob, decision, and reason_codes added.
    """
    missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"[scorer] Missing columns in {source} data: {missing}")

    # Scale using centralized utility — same function used by Phase 6 pipeline
    df_scaled = preprocess_and_scale(df)

    X    = df_scaled[FEATURE_COLUMNS]
    df   = df.copy()
    df["predicted_prob"] = model.predict_proba(X)[:, 1]
    df["source"]         = source
    df   = classify_all(df)
    df["reason_codes"]   = extract_all_reason_codes(df)
    return df


def validate_risk_tiers(df: pd.DataFrame, source: str) -> None:
    """
    Check whether the model correctly identified the designed risk tiers.

    Prints a tier-by-tier accuracy summary showing what percentage of
    intentionally low/moderate/high risk applicants were correctly classified.

    Parameters
    ----------
    df : pd.DataFrame
        Scored DataFrame with decision column.
    source : str
        Label for the data source.
    """
    print(f"\n── {source} Risk Tier Validation ──────────────────────────")

    tiers = [
        ("LOW RISK",      slice(*LOW_RISK_ROWS),      "Approved"),
        ("MODERATE RISK", slice(*MODERATE_RISK_ROWS), None),
        ("HIGH RISK",     slice(*HIGH_RISK_ROWS),      "Denied"),
    ]

    for tier_name, slc, expected_decision in tiers:
        tier_df = df.iloc[slc]
        if len(tier_df) == 0:
            print(f"  {tier_name}: no rows in this tier")
            continue

        mean_prob = tier_df["predicted_prob"].mean()
        decisions = tier_df["decision"].value_counts().to_dict()

        print(f"\n  {tier_name} ({len(tier_df)} applicants):")
        print(f"    Mean predicted prob: {mean_prob:.4f}")
        print(f"    Decisions: {decisions}")

        if expected_decision:
            correct = (tier_df["decision"] == expected_decision).sum()
            pct     = correct / len(tier_df) * 100
            print(f"    Correctly classified as '{expected_decision}': "
                  f"{correct}/{len(tier_df)} ({pct:.1f}%)")


def print_summary(combined: pd.DataFrame) -> None:
    """Print overall scoring summary across all sources."""
    print("\n" + "=" * 60)
    print("  SYNTHETIC SCORING SUMMARY")
    print("=" * 60)

    for source in SYNTHETIC_SOURCES.keys():
        subset = combined[combined["source"] == source]
        if len(subset) == 0:
            continue
        print(f"\n  {source} ({len(subset)} applicants):")
        print(f"    Mean predicted prob: {subset['predicted_prob'].mean():.4f}")
        print(f"    Min: {subset['predicted_prob'].min():.4f} "
              f"Max: {subset['predicted_prob'].max():.4f}")
        for decision, count in subset["decision"].value_counts().items():
            print(f"    {decision}: {count} ({count/len(subset)*100:.1f}%)")

    print(f"\n  Combined ({len(combined)} applicants across "
          f"{len(SYNTHETIC_SOURCES)} AI sources):")
    print(f"    Mean predicted prob: {combined['predicted_prob'].mean():.4f}")
    for decision, count in combined["decision"].value_counts().items():
        print(f"    {decision}: {count} ({count/len(combined)*100:.1f}%)")
    print("=" * 60)


if __name__ == "__main__":
    print("=" * 60)
    print("  SYNTHETIC APPLICANT SCORING — 4 AI SOURCES")
    print("=" * 60)

    # Load champion model
    model = load_champion_model()

    # Load and score all four datasets
    print("\n[scorer] Loading synthetic datasets...")
    scored_datasets = {}

    for source, path in SYNTHETIC_SOURCES.items():
        if not os.path.exists(path):
            print(f"[scorer] WARNING — {source} file not found: {path}")
            continue
        df = pd.read_csv(path)
        print(f"[scorer] {source}: {len(df)} rows loaded")
        print(f"\n[scorer] Scoring {source} applicants...")
        scored_datasets[source] = score_dataframe(df, model, source)

    # Validate risk tiers for each source
    for source, scored_df in scored_datasets.items():
        validate_risk_tiers(scored_df, source)

    # Combine all scored datasets
    combined = pd.concat(list(scored_datasets.values()), ignore_index=True)

    # Convert reason_codes list to pipe-delimited string for CSV
    combined["reason_codes"] = combined["reason_codes"].apply(
        lambda x: " | ".join(x) if x else ""
    )

    os.makedirs("outputs", exist_ok=True)
    combined.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[scorer] Results saved: {OUTPUT_CSV}")

    # Print summary
    print_summary(combined)

    print("\n  Ready for Phase 7 — Dashboards.")